### ISSUE TITLE
Exclusive option and back button

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/RankingIsotope#2]
[Ranking_Example.zip](https://github.com/AskiaADX/RankingIsotope/files/1394164/Ranking_Example.zip)
Hi

If I select the exclusive answer "Don't know", click Next to go to the following question, and then click "Back" to the ranking question it looks like this:
![ranking](https://user-images.githubusercontent.com/20987595/31712201-454ee8d0-b3f2-11e7-964d-771461ff3cdf.PNG)

Instead of:
![rankingother](https://user-images.githubusercontent.com/20987595/31712209-4add0070-b3f2-11e7-953b-b3bb1be04f0c.PNG)

This is fine in the RankingIsotopeOther adc.

I'm attaching a qex with both questions.

Thanks
Diana

**Comment by Djedj** [comment]
Hi @diana1357,

Did you set Last option exclusive to Yes ?

Best Regards

**Comment by diana1357** [comment]
yes, it is.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by Djedj** [comment]
Hi @diana1357 

Should be fixed in v2.0.2.

Let us know if it makes the trick ?

Best Regards

**Comment by diana1357** [comment]
Thank you @Djedj  - it works now!
